<a href="https://colab.research.google.com/github/Chelladuraimct/ColabFiles/blob/main/Chelladurai_R_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1: Create the Data Array

In [ ]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

**Task 1**:

1. Print the shape of data

(4 weather stations, 5 daily readings each)

In [ ]:
# Print shape
print("Shape of data:", data.shape)

Shape of data: (4, 5)


2.Compute and print mean temperature per station (row-wise mean)

In [ ]:
# Mean temperature per station (row-wise mean)
mean_per_station = np.mean(data, axis=1)
print("Mean temperature per station:", mean_per_station)

Mean temperature per station: [25.3  23.78 26.58 25.26]


**Task 2**:

Extract all temperature readings above 28.0°C

In [ ]:
# Boolean mask for values above 28°C
above_28 = data[data > 28.0]

print("Temperatures above 28°C:", above_28)

Temperatures above 28°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


**Task 3**:

Normalize entire array to range [0, 1]

Formula:
normalized=(data-data.min())/(data.max()-data.min())

In [ ]:
# Normalize the data
normalized = (data - data.min()) / (data.max() - data.min())

# Round to 2 decimal places
normalized_rounded = np.round(normalized, 2)

print("Normalized data:\n", normalized_rounded)

Normalized data:
 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
